var items = {
  "login": "maswhitaker",
  "id": 7285459,
  "avatar_url": "https://avatars.githubusercontent.com/u/7285459?",
  "gravatar_id": "3d539bab05359808b810c283a944ee94",
  "url": "https://api.github.com/users/maswhitaker",
  "html_url": "https://github.com/maswhitaker",
  "followers_url": "https://api.github.com/users/maswhitaker/followers",
  "following_url": "https://api.github.com/users/maswhitaker/following{/other_user}",
  "gists_url": "https://api.github.com/users/maswhitaker/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/maswhitaker/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/maswhitaker/subscriptions",
  "organizations_url": "https://api.github.com/users/maswhitaker/orgs",
  "repos_url": "https://api.github.com/users/maswhitaker/repos",
  "events_url": "https://api.github.com/users/maswhitaker/events{/privacy}",
  "received_events_url": "https://api.github.com/users/maswhitaker/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Mason F Whitaker",
  "company": "",
  "blog": "http://www.masonwhitaker.com/",
  "location": "Boone, NC",
  "email": "masforwhi@yahoo.com",
  "hireable": false,
  "bio": null,
  "public_repos": 5,
  "public_gists": 2,
  "followers": 4,
  "following": 8,
  "created_at": "2014-04-14T03:28:32Z",
  "updated_at": "2014-06-19T05:20:00Z"
};
var infolog = $("#information").html();
$("#target").append(_.template(infolog,items));
